### ISSUE TITLE
Add active flag for user accounts

### ISSUE THREAD

**Issue by achakavarti** [drewwmercer/developer-ocs#102]
User accounts will need to be associated with a status so that later the admin can control spam or deactivated users.

**Comment by JoshHeng** [comment]
Can I take this?

**Comment by JoshHeng** [comment]
How are users saved/persisted in the database? All I can see in the database schema is the database being created, but nothing else

**Comment by drewwmercer** [comment]
Flag is already present in the user.js model.

**Comment by JoshHeng** [comment]
Is this already fixed?
