### ISSUE TITLE
Update logo effect in header

### ISSUE THREAD

**Issue by drewwmercer** [drewwmercer/developer-ocs#60]
Use some logo effect to make it slightly more visible against the banner

**Comment by davidbru** [comment]
I think my proposed pull request fixes the issue quite nicely and even should work cross browser.

**Comment by drewwmercer** [comment]
Before
![screen shot 2018-10-03 at 7 56 27 am](https://user-images.githubusercontent.com/20029745/46408966-e531fd80-c6e1-11e8-9c63-9d5d32b99925.png)

After
![screen shot 2018-10-03 at 7 56 34 am](https://user-images.githubusercontent.com/20029745/46408971-eb27de80-c6e1-11e8-8eff-d6e1f685398b.png)
